# Generated by Django 4.2.11 on 2024-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naviny', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
