# Generated by Django 4.2.11 on 2024-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviny', '0002_rename_article_articles_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.FloatField(default=1, verbose_name='Стоимость работ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Порода животного'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип животного'),
        ),
    ]
