# Generated by Django 4.2.11 on 2024-04-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviny', '0003_articles_price_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
